"""
This file is used to generate a set of labelled stimuli (each belonging to either category 0 or 1)
according to various rules. Transformation functions from the transform module are used extensively. see comment below.

To view all possible transformation functions (they are the same wheter applied to set or to origin)
simply import the transform module from generation "from generation import transform" and look at the
available functions, or check the functions in the generation.transform modules by viewing the files in that module
"""
# %%
from tools import set_tools
def make_set_from_specs(frequency, number_of_neurons, stimulus_duration,
                        set_size, set_transform_function, set_transform_params,
                        origin_transform_function=None, origin_transform_params=None,
                        fixed_frequency=False):
    """
    This function accepts specifications for stimulus creation,
    creates two stimuli with these specifications,
    and then applies the set_transform_function with set_transform_params to each
    stimulus, collecting the transformed versions of both stimuli into the stimuli_set.

    if origin_transform_function AND origin_transform_params are specified,
    One original stimulus will be generated with the desired specs,
    whereas the other will be generated by applying origin_transform_function with origin_transform_params
    to that same stimulus.



    :param frequency: The average firing frequency of each neuron in the sample, units: Hz
    :param number_of_neurons:  Number of neurons in the stimulus, units: Integer
    :param stimulus_duration: Maximal duration of the stimuli, units: ms
    :param set_size: number of stimuli in the final set, an equal number is generated from each original stimulus
    :param set_transform_function: A transformation from generation.transform to be applied to the original stimuli
    :param set_transform_params: The parameters to be used with set_transformation_function
    :param origin_transform_function: A transformation from generation.transform to be applied to one original stimulus in order to generate the other
    :param origin_transform_params: The parameters to be used with origin_transform_function
    :param fixed_frequency:
    """
    pass

def make_set_from_stimuli(original_stimuli, stimulus_duration,
                          set_size, set_transform_function, set_transform_params):
    """
    This function takes two original_stimuli of identical stimulus_duration,
    and applies the set_transform_function with set_transform_params to each
    stimulus, collecting the transformed versions of both stimuli into the stimuli_set

    :param original_stimuli: A tuple containing two stimuli, each consisting of a collections of neurons and their spike-times
    :param set_size: number of stimuli in the final set, an equal number is generated from each original stimulus
    :param stimulus_duration: Maximal duration of the stimulus, units: ms
    :param set_transform_function: A transformation from generation.transform to be applied to the original stimuli
    :param set_transform_params: The parameters to be used with set_transformation_function
    :return:
    """

    pass
